services:
  suricata:
    build:
      context: ./bicep-suricata
      args:
        - BASE_IMAGE=maxldwg/suricata
        - VERSION=7.0.5
    ports: 
      - 8000:4329
    volumes:
      - ./bicep-suricata/:/opt/code
    network_mode: host
    environment:
      - PORT=4220
      - IDS_MODULE=src.models.suricata
      - IDS_CLASS=Suricata
    command: sh -c 'fastapi dev /opt/code/src/main.py --host 0.0.0.0 --port $$PORT'
